/*
 * DocRaptor
 *
 * A native client library for the DocRaptor HTML to PDF/XLS service.
 *
 * The version of the OpenAPI document: 2.0.0
 *
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using DocRaptor.Api;
using DocRaptor.Model;
using DocRaptor.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace DocRaptor.Test
{
    /// <summary>
    ///  Class for testing AsyncDoc
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class AsyncDocTests
    {
        // TODO uncomment below to declare an instance variable for AsyncDoc
        //private AsyncDoc instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of AsyncDoc
            //instance = new AsyncDoc();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of AsyncDoc
        /// </summary>
        [Test]
        public void AsyncDocInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOf" AsyncDoc
            //Assert.IsInstanceOf(typeof(AsyncDoc), instance);
        }


        /// <summary>
        /// Test the property 'StatusId'
        /// </summary>
        [Test]
        public void StatusIdTest()
        {
            // TODO unit test for the property 'StatusId'
        }

    }

}
