/*
 * DocRaptor
 *
 * A native client library for the DocRaptor HTML to PDF/XLS service.
 *
 * The version of the OpenAPI document: 2.0.0
 *
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using DocRaptor.Api;
using DocRaptor.Model;
using DocRaptor.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace DocRaptor.Test
{
    /// <summary>
    ///  Class for testing DocStatus
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class DocStatusTests
    {
        // TODO uncomment below to declare an instance variable for DocStatus
        //private DocStatus instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of DocStatus
            //instance = new DocStatus();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of DocStatus
        /// </summary>
        [Test]
        public void DocStatusInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOf" DocStatus
            //Assert.IsInstanceOf(typeof(DocStatus), instance);
        }


        /// <summary>
        /// Test the property 'Status'
        /// </summary>
        [Test]
        public void StatusTest()
        {
            // TODO unit test for the property 'Status'
        }
        /// <summary>
        /// Test the property 'DownloadUrl'
        /// </summary>
        [Test]
        public void DownloadUrlTest()
        {
            // TODO unit test for the property 'DownloadUrl'
        }
        /// <summary>
        /// Test the property 'DownloadId'
        /// </summary>
        [Test]
        public void DownloadIdTest()
        {
            // TODO unit test for the property 'DownloadId'
        }
        /// <summary>
        /// Test the property 'Message'
        /// </summary>
        [Test]
        public void MessageTest()
        {
            // TODO unit test for the property 'Message'
        }
        /// <summary>
        /// Test the property 'NumberOfPages'
        /// </summary>
        [Test]
        public void NumberOfPagesTest()
        {
            // TODO unit test for the property 'NumberOfPages'
        }
        /// <summary>
        /// Test the property 'ValidationErrors'
        /// </summary>
        [Test]
        public void ValidationErrorsTest()
        {
            // TODO unit test for the property 'ValidationErrors'
        }

    }

}
