/*
 * DocRaptor
 *
 * A native client library for the DocRaptor HTML to PDF/XLS service.
 *
 * The version of the OpenAPI document: 2.0.0
 *
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using DocRaptor.Api;
using DocRaptor.Model;
using DocRaptor.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace DocRaptor.Test
{
    /// <summary>
    ///  Class for testing Doc
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class DocTests
    {
        // TODO uncomment below to declare an instance variable for Doc
        //private Doc instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of Doc
            //instance = new Doc();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of Doc
        /// </summary>
        [Test]
        public void DocInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOf" Doc
            //Assert.IsInstanceOf(typeof(Doc), instance);
        }


        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Test]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
        /// <summary>
        /// Test the property 'DocumentType'
        /// </summary>
        [Test]
        public void DocumentTypeTest()
        {
            // TODO unit test for the property 'DocumentType'
        }
        /// <summary>
        /// Test the property 'DocumentContent'
        /// </summary>
        [Test]
        public void DocumentContentTest()
        {
            // TODO unit test for the property 'DocumentContent'
        }
        /// <summary>
        /// Test the property 'DocumentUrl'
        /// </summary>
        [Test]
        public void DocumentUrlTest()
        {
            // TODO unit test for the property 'DocumentUrl'
        }
        /// <summary>
        /// Test the property 'Test'
        /// </summary>
        [Test]
        public void TestTest()
        {
            // TODO unit test for the property 'Test'
        }
        /// <summary>
        /// Test the property 'Pipeline'
        /// </summary>
        [Test]
        public void PipelineTest()
        {
            // TODO unit test for the property 'Pipeline'
        }
        /// <summary>
        /// Test the property 'Strict'
        /// </summary>
        [Test]
        public void StrictTest()
        {
            // TODO unit test for the property 'Strict'
        }
        /// <summary>
        /// Test the property 'IgnoreResourceErrors'
        /// </summary>
        [Test]
        public void IgnoreResourceErrorsTest()
        {
            // TODO unit test for the property 'IgnoreResourceErrors'
        }
        /// <summary>
        /// Test the property 'IgnoreConsoleMessages'
        /// </summary>
        [Test]
        public void IgnoreConsoleMessagesTest()
        {
            // TODO unit test for the property 'IgnoreConsoleMessages'
        }
        /// <summary>
        /// Test the property 'Tag'
        /// </summary>
        [Test]
        public void TagTest()
        {
            // TODO unit test for the property 'Tag'
        }
        /// <summary>
        /// Test the property 'Help'
        /// </summary>
        [Test]
        public void HelpTest()
        {
            // TODO unit test for the property 'Help'
        }
        /// <summary>
        /// Test the property 'Javascript'
        /// </summary>
        [Test]
        public void JavascriptTest()
        {
            // TODO unit test for the property 'Javascript'
        }
        /// <summary>
        /// Test the property 'Referrer'
        /// </summary>
        [Test]
        public void ReferrerTest()
        {
            // TODO unit test for the property 'Referrer'
        }
        /// <summary>
        /// Test the property 'CallbackUrl'
        /// </summary>
        [Test]
        public void CallbackUrlTest()
        {
            // TODO unit test for the property 'CallbackUrl'
        }
        /// <summary>
        /// Test the property 'HostedDownloadLimit'
        /// </summary>
        [Test]
        public void HostedDownloadLimitTest()
        {
            // TODO unit test for the property 'HostedDownloadLimit'
        }
        /// <summary>
        /// Test the property 'HostedExpiresAt'
        /// </summary>
        [Test]
        public void HostedExpiresAtTest()
        {
            // TODO unit test for the property 'HostedExpiresAt'
        }
        /// <summary>
        /// Test the property 'PrinceOptions'
        /// </summary>
        [Test]
        public void PrinceOptionsTest()
        {
            // TODO unit test for the property 'PrinceOptions'
        }

    }

}
