/*
 * DocRaptor
 *
 * A native client library for the DocRaptor HTML to PDF/XLS service.
 *
 * The version of the OpenAPI document: 2.0.0
 *
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using DocRaptor.Api;
using DocRaptor.Model;
using DocRaptor.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace DocRaptor.Test
{
    /// <summary>
    ///  Class for testing PrinceOptions
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class PrinceOptionsTests
    {
        // TODO uncomment below to declare an instance variable for PrinceOptions
        //private PrinceOptions instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of PrinceOptions
            //instance = new PrinceOptions();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of PrinceOptions
        /// </summary>
        [Test]
        public void PrinceOptionsInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOf" PrinceOptions
            //Assert.IsInstanceOf(typeof(PrinceOptions), instance);
        }


        /// <summary>
        /// Test the property 'Baseurl'
        /// </summary>
        [Test]
        public void BaseurlTest()
        {
            // TODO unit test for the property 'Baseurl'
        }
        /// <summary>
        /// Test the property 'NoXinclude'
        /// </summary>
        [Test]
        public void NoXincludeTest()
        {
            // TODO unit test for the property 'NoXinclude'
        }
        /// <summary>
        /// Test the property 'NoNetwork'
        /// </summary>
        [Test]
        public void NoNetworkTest()
        {
            // TODO unit test for the property 'NoNetwork'
        }
        /// <summary>
        /// Test the property 'NoParallelDownloads'
        /// </summary>
        [Test]
        public void NoParallelDownloadsTest()
        {
            // TODO unit test for the property 'NoParallelDownloads'
        }
        /// <summary>
        /// Test the property 'HttpUser'
        /// </summary>
        [Test]
        public void HttpUserTest()
        {
            // TODO unit test for the property 'HttpUser'
        }
        /// <summary>
        /// Test the property 'HttpPassword'
        /// </summary>
        [Test]
        public void HttpPasswordTest()
        {
            // TODO unit test for the property 'HttpPassword'
        }
        /// <summary>
        /// Test the property 'HttpProxy'
        /// </summary>
        [Test]
        public void HttpProxyTest()
        {
            // TODO unit test for the property 'HttpProxy'
        }
        /// <summary>
        /// Test the property 'HttpTimeout'
        /// </summary>
        [Test]
        public void HttpTimeoutTest()
        {
            // TODO unit test for the property 'HttpTimeout'
        }
        /// <summary>
        /// Test the property 'Insecure'
        /// </summary>
        [Test]
        public void InsecureTest()
        {
            // TODO unit test for the property 'Insecure'
        }
        /// <summary>
        /// Test the property 'Media'
        /// </summary>
        [Test]
        public void MediaTest()
        {
            // TODO unit test for the property 'Media'
        }
        /// <summary>
        /// Test the property 'NoAuthorStyle'
        /// </summary>
        [Test]
        public void NoAuthorStyleTest()
        {
            // TODO unit test for the property 'NoAuthorStyle'
        }
        /// <summary>
        /// Test the property 'NoDefaultStyle'
        /// </summary>
        [Test]
        public void NoDefaultStyleTest()
        {
            // TODO unit test for the property 'NoDefaultStyle'
        }
        /// <summary>
        /// Test the property 'NoEmbedFonts'
        /// </summary>
        [Test]
        public void NoEmbedFontsTest()
        {
            // TODO unit test for the property 'NoEmbedFonts'
        }
        /// <summary>
        /// Test the property 'NoSubsetFonts'
        /// </summary>
        [Test]
        public void NoSubsetFontsTest()
        {
            // TODO unit test for the property 'NoSubsetFonts'
        }
        /// <summary>
        /// Test the property 'NoCompress'
        /// </summary>
        [Test]
        public void NoCompressTest()
        {
            // TODO unit test for the property 'NoCompress'
        }
        /// <summary>
        /// Test the property 'Encrypt'
        /// </summary>
        [Test]
        public void EncryptTest()
        {
            // TODO unit test for the property 'Encrypt'
        }
        /// <summary>
        /// Test the property 'KeyBits'
        /// </summary>
        [Test]
        public void KeyBitsTest()
        {
            // TODO unit test for the property 'KeyBits'
        }
        /// <summary>
        /// Test the property 'UserPassword'
        /// </summary>
        [Test]
        public void UserPasswordTest()
        {
            // TODO unit test for the property 'UserPassword'
        }
        /// <summary>
        /// Test the property 'OwnerPassword'
        /// </summary>
        [Test]
        public void OwnerPasswordTest()
        {
            // TODO unit test for the property 'OwnerPassword'
        }
        /// <summary>
        /// Test the property 'DisallowPrint'
        /// </summary>
        [Test]
        public void DisallowPrintTest()
        {
            // TODO unit test for the property 'DisallowPrint'
        }
        /// <summary>
        /// Test the property 'DisallowCopy'
        /// </summary>
        [Test]
        public void DisallowCopyTest()
        {
            // TODO unit test for the property 'DisallowCopy'
        }
        /// <summary>
        /// Test the property 'DisallowAnnotate'
        /// </summary>
        [Test]
        public void DisallowAnnotateTest()
        {
            // TODO unit test for the property 'DisallowAnnotate'
        }
        /// <summary>
        /// Test the property 'DisallowModify'
        /// </summary>
        [Test]
        public void DisallowModifyTest()
        {
            // TODO unit test for the property 'DisallowModify'
        }
        /// <summary>
        /// Test the property 'Debug'
        /// </summary>
        [Test]
        public void DebugTest()
        {
            // TODO unit test for the property 'Debug'
        }
        /// <summary>
        /// Test the property 'Input'
        /// </summary>
        [Test]
        public void InputTest()
        {
            // TODO unit test for the property 'Input'
        }
        /// <summary>
        /// Test the property '_Version'
        /// </summary>
        [Test]
        public void _VersionTest()
        {
            // TODO unit test for the property '_Version'
        }
        /// <summary>
        /// Test the property 'Javascript'
        /// </summary>
        [Test]
        public void JavascriptTest()
        {
            // TODO unit test for the property 'Javascript'
        }
        /// <summary>
        /// Test the property 'CssDpi'
        /// </summary>
        [Test]
        public void CssDpiTest()
        {
            // TODO unit test for the property 'CssDpi'
        }
        /// <summary>
        /// Test the property 'Profile'
        /// </summary>
        [Test]
        public void ProfileTest()
        {
            // TODO unit test for the property 'Profile'
        }
        /// <summary>
        /// Test the property 'PdfTitle'
        /// </summary>
        [Test]
        public void PdfTitleTest()
        {
            // TODO unit test for the property 'PdfTitle'
        }
        /// <summary>
        /// Test the property 'Iframes'
        /// </summary>
        [Test]
        public void IframesTest()
        {
            // TODO unit test for the property 'Iframes'
        }
        /// <summary>
        /// Test the property 'PageMargin'
        /// </summary>
        [Test]
        public void PageMarginTest()
        {
            // TODO unit test for the property 'PageMargin'
        }
        /// <summary>
        /// Test the property 'PdfForms'
        /// </summary>
        [Test]
        public void PdfFormsTest()
        {
            // TODO unit test for the property 'PdfForms'
        }

    }

}
