#!/bin/bash
set -e
cd "$(dirname "$0")/.."

if [[ $(ls bin/DocRaptor*.nupkg) ]] && [ "$1" == "lazy" ]; then
  exit
fi

# check dependencies
which mono > /dev/null || (echo "mono must be installed"; exit 1)
which mcs > /dev/null  || (echo "mcs must be installed"; exit 1)

./build.sh

script/nuget pack -OutputDirectory bin/

link="bin/Newtonsoft.Json.dll bin/JsonSubTypes.dll bin/RestSharp.dll"

mono vendor/ILRepack.exe /internalize /out:bin/DocRaptorWithDependencies.dll bin/DocRaptor.dll $link
