#!/bin/bash
set -e
cd "`dirname \"$0\"`/.."

if [[ `ls build/docraptor*.nupkg` ]] && [ "$1" == "lazy" ]; then
  exit
fi

which mono > /dev/null || (echo "mono must be installed"; exit 1)
which mcs > /dev/null  || (echo "mcs must be installed"; exit 1)

MINIMAL_DOCRAPTOR_LIB="build/docraptor-minimal.dll"
EVERYTHING_DOCRAPTOR_LIB="build/docraptor-all.dll"

rm -rf build/
mkdir build

mcs -lib:bin -reference:Newtonsoft.Json.dll,RestSharp.dll,System.Runtime.Serialization.dll -target:library -out:$MINIMAL_DOCRAPTOR_LIB -recurse:src/*.cs

mono vendor/ILRepack.exe /internalize /out:$EVERYTHING_DOCRAPTOR_LIB $MINIMAL_DOCRAPTOR_LIB bin/*.dll

mono vendor/nuget.exe pack -OutputDirectory build/
