#!/bin/bash
set -e
cd "`dirname \"$0\"`/.."

if [[ `ls bin/docraptor*.nupkg` ]] && [ "$1" == "lazy" ]; then
  exit
fi

# check dependencies
which mono > /dev/null || (echo "mono must be installed"; exit 1)
which mcs > /dev/null  || (echo "mcs must be installed"; exit 1)

mono vendor/nuget.exe install vendor/packages.config -o vendor
mkdir -p bin

references=vendor/Newtonsoft.Json.8.0.2/lib/net45/Newtonsoft.Json.dll,vendor/RestSharp.105.2.3/lib/net45/RestSharp.dll,System.Runtime.Serialization.dll
mcs -sdk:45 \
  -r:$references \
  -target:library \
  -out:bin/DocRaptor.dll \
  -recurse:'src/*.cs' \
  -doc:bin/DocRaptor.xml \
  -platform:anycpu

mono vendor/nuget.exe pack -OutputDirectory bin/

link=`echo $references | sed 's/,/ /g' | sed -E 's/ System\..*\.dll//'`
mono vendor/ILRepack.exe /internalize /out:bin/DocRaptorWithDependencies.dll bin/DocRaptor.dll $link
