#!/bin/bash
set -e
cd "`dirname \"$0\"`/.."

./script/build

# runs a test file with PASS/FAIL message
run_test() {
  ./script/run_csharp_file $1 && echo "PASS $1" || (echo "FAIL $1"; exit 1)
}

if [ "$1" == "" ]; then
  for test in $(ls test/*.cs); do
    run_test $test
  done
else
  run_test $1.cs
fi
