#!/bin/bash
set -e
cd "`dirname \"$0\"`/.."

./script/build

cp build/*.dll test/

compile_and_run() {
  base_name=`basename -s .cs $1`
  mcs -lib:build/ -reference:docraptor-all.dll test/$base_name.cs -out:test/$base_name.exe
  mono test/$base_name.exe
}

# runs a test file with PASS/FAIL message
run_test() {
  compile_and_run $1 && echo "PASS $1" || (echo "FAIL $1"; exit 1)
}

if [ "$1" == "" ]; then
  for test in $(ls test/*.cs); do
    run_test $test
  done
else
  run_test $1.cs
fi
