#!/bin/sh
set -ex
cd "`dirname \"$0\"`/.."

./script/build

cp build/*.dll test/

compile_and_run() {
  base_name=`basename -s .cs $1`
  mcs -lib:build/ -reference:docraptor-all.dll test/$base_name.cs -out:test/$base_name.exe
  mono test/$base_name.exe
}

if [ "$1" == "" ]; then
  for test in $(ls test/*.cs); do
    compile_and_run $test
  done
else
  compile_and_run $1.cs
fi
